type ProductData = {
  id: number;
  name: string;
  description: string;
  price: number;
  image: string;
  article: string;
  country: string;
  gender: string;
  typeOfMechanism: string;
};

export const CATALOG: ProductData[] = [
  {
    id: 1,
    name: 'Rolex Submariner',
    description: 'Легендарные дайверские часы с автоподзаводом. Водонепроницаемость 300м, керамический безель.',
    price: 45000,
    image: 'https://static.alltime.ru/obj/catalog/watch/slava/img/normal2020/2800900-300-2409.jpg',
    article: 'ROLEX-SUB-001',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 2,
    name: 'Omega Speedmaster',
    description: 'Знаменитые «лунные» часы, первые побывавшие на Луне. Хронограф, ручной завод.',
    price: 32000,
    image: 'https://static.alltime.ru/obj/catalog/watch/seiko/img/normal2020/SPB103.jpg',
    article: 'OMEGA-SPEED-002',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Механический с ручным заводом',
  },
  {
    id: 3,
    name: 'Casio G-Shock',
    description: 'Сверхпрочные цифровые часы с ударопрочным корпусом. 20-ти бар водонепроницаемость.',
    price: 15000,
    image: 'https://static.alltime.ru/obj/catalog/watch/maserati/img/normal2020/R8823118010.jpg',
    article: 'CASIO-GSH-003',
    country: 'Япония',
    gender: 'Унисекс',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 4,
    name: 'Seiko Presage',
    description: 'Японские механические часы с сапфировым стеклом. Классический дизайн с открытой задней крышкой.',
    price: 85000,
    image: 'https://static.alltime.ru/obj/catalog/watch/agelocer/img/normal2020/5815A5-R.jpg',
    article: 'SEIKO-PRES-004',
    country: 'Япония',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 5,
    name: 'Apple Watch Series 9',
    description: 'Умные часы с функцией ECG и отслеживанием активности. Always-On дисплей, iOS интеграция.',
    price: 26000,
    image: 'https://static.alltime.ru/obj/catalog/watch/rodania/img/normal2020/R18053.jpg',
    article: 'APPLE-W9-005',
    country: 'США',
    gender: 'Унисекс',
    typeOfMechanism: 'Электронный',
  },
  {
    id: 6,
    name: 'Tissot Le Locle',
    description: 'Элегантные швейцарские часы с автоподзаводом. Классический дизайн, сапфировое стекло.',
    price: 28000,
    image: 'https://static.alltime.ru/obj/catalog/watch/titoni/img/normal2020/83188-S-575.jpg',
    article: 'TISSOT-LL-006',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 7,
    name: 'Cartier Tank',
    description: 'Икона стиля ар-деко. Кварцевый механизм, прямоугольный корпус, римские цифры.',
    price: 92000,
    image: 'https://static.alltime.ru/obj/catalog/watch/longines/img/normal2020/L5-200-4-75-5.jpg',
    article: 'CARTIER-TANK-007',
    country: 'Франция',
    gender: 'Женские',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 8,
    name: 'Orient Bambino',
    description: 'Бюджетные механические часы с классическим дизайном. Автоподзавод, кожаный ремешок.',
    price: 12000,
    image: 'https://static.alltime.ru/obj/catalog/watch/raymondweil/img/normal2020/2780-STC-52001.jpg',
    article: 'ORIENT-BAM-008',
    country: 'Япония',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 9,
    name: 'Patek Philippe Nautilus',
    description: 'Элитные часы с автоматическим механизмом. Стальной корпус, фирменный дизайн безеля.',
    price: 145000,
    image: 'https://static.alltime.ru/obj/catalog/watch/tagheuer/img/normal2020/WBN2316-BA0001.jpg',
    article: 'PATEK-NAUT-009',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 10,
    name: 'Breitling Navitimer',
    description: 'Авиационные часы со встроенным хронографом и логарифмической линейкой. Легенда авиации.',
    price: 78000,
    image: 'https://static.alltime.ru/obj/catalog/watch/rado/img/normal2020/R32105313.jpg',
    article: 'BREITLING-NAV-010',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 11,
    name: 'Tag Heuer Carrera',
    description: 'Спортивные часы с хронографом. Легендарная коллекция, вдохновленная автоспортом.',
    price: 68000,
    image: 'https://static.alltime.ru/obj/catalog/watch/citizen/img/normal2020/AT8020-54L.jpg',
    article: 'TAG-CARRERA-013',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 12,
    name: 'Longines HydroConquest',
    description: 'Дайверские часы с водонепроницаемостью 300м. Прочный корпус, вращающийся безель.',
    price: 52000,
    image: 'https://static.alltime.ru/obj/catalog/watch/emporio-armani/img/normal2020/AR2448.jpg',
    article: 'LONGINES-HYDRO-014',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 13,
    name: 'Hamilton Khaki Field',
    description: 'Военные часы с автоподзаводом. Классический полевой дизайн, высокая надежность.',
    price: 38000,
    image: 'https://static.alltime.ru/obj/catalog/watch/cuervo-y-sobrinos/img/normal2020/3144-1NF.jpg',
    article: 'HAMILTON-KHAKI-015',
    country: 'США',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 14,
    name: 'Tudor Black Bay',
    description: 'Наследник легендарных дайверских часов. Винтажный дизайн, современная начинка.',
    price: 89000,
    image: 'https://static.alltime.ru/obj/catalog/watch/liu-jo/img/normal2020/TLJ2333.jpg',
    article: 'TUDOR-BB-016',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 15,
    name: 'Citizen Eco-Drive',
    description: 'Часы с технологией зарядки от света. Не требуют замены батареек, экологичны.',
    price: 22000,
    image: 'https://static.alltime.ru/obj/catalog/watch/orient/img/normal2020/AG03002B.jpg',
    article: 'CITIZEN-ECO-017',
    country: 'Япония',
    gender: 'Мужские',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 16,
    name: 'Jaeger-LeCoultre Reverso',
    description: 'Культовые часы с переворачивающимся корпусом. Ар-деко дизайн, ручной завод.',
    price: 156000,
    image: 'https://static.alltime.ru/obj/catalog/watch/casio/img/normal2020/GA-2100HDS-7A.jpg',
    article: 'JLC-REVERSO-018',
    country: 'Швейцария',
    gender: 'Унисекс',
    typeOfMechanism: 'Механический с ручным заводом',
  },
  {
    id: 17,
    name: 'Bulova Precisionist',
    description: 'Высокоточные кварцевые часы. Плавное движение секундной стрелки, уникальный механизм.',
    price: 29000,
    image: 'https://static.alltime.ru/obj/catalog/watch/lacoste/img/normal2020/2011244.jpg',
    article: 'BULOVA-PREC-019',
    country: 'США',
    gender: 'Мужские',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 18,
    name: 'Panerai Luminor',
    description: 'Итальянские дайверские часы. Массивный корпус, фирменная система защиты заводной головки.',
    price: 112000,
    image: 'https://static.alltime.ru/obj/catalog/watch/nika/img/normal2020/0111B-2-9-81B.jpg',
    article: 'PANERAI-LUM-020',
    country: 'Италия',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 19,
    name: 'Movado Museum',
    description: 'Минималистичные часы с культовым дизайном. Золотая точка на циферблате - символ бренда.',
    price: 45000,
    image: 'https://static.alltime.ru/obj/catalog/watch/stuhrling/img/normal2020/3917-1.jpg',
    article: 'MOVADO-MUSEUM-021',
    country: 'Швейцария',
    gender: 'Унисекс',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 20,
    name: 'Hublot Big Bang',
    description: 'Современные часы из высокотехнологичных материалов. Фирменный дизайн "сэндвич".',
    price: 198000,
    image: 'https://static.alltime.ru/obj/catalog/watch/tommy-hilfiger/img/normal2020/1791788.jpg',
    article: 'HUBLOT-BB-022',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 21,
    name: 'Fossil Townsman',
    description: 'Стильные часы в ретро-стиле. Кожаный ремешок, римские цифры, классический дизайн.',
    price: 15000,
    image: 'https://static.alltime.ru/obj/catalog/watch/daniel-wellington/img/normal2020/DW00100472.jpg',
    article: 'FOSSIL-TOWN-025',
    country: 'США',
    gender: 'Мужские',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 22,
    name: 'IWC Portugieser',
    description: 'Морские хронометры с элегантным дизайном. Большой циферблат, арабские цифры.',
    price: 134000,
    image: 'https://static.alltime.ru/obj/catalog/watch/michael-kors/img/normal2020/MK3215.jpg',
    article: 'IWC-PORT-026',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 23,
    name: 'Garmin Fenix 7',
    description: 'Многофункциональные спортивные смарт-часы. GPS, пульсометр, трекинг активности.',
    price: 58000,
    image: 'https://static.alltime.ru/obj/catalog/watch/mathey-tissot/img/normal2020/H810BDI.jpg',
    article: 'GARMIN-FENIX-027',
    country: 'США',
    gender: 'Унисекс',
    typeOfMechanism: 'Электронный',
  },
  {
    id: 24,
    name: 'Chopard Happy Diamonds',
    description: 'Роскошные часы с плавающими бриллиантами. Элегантный дизайн, уникальная технология.',
    price: 187000,
    image: 'https://static.alltime.ru/obj/catalog/watch/boccia-titanium/img/normal2020/3331-05.jpg',
    article: 'CHOPARD-HAPPY-028',
    country: 'Швейцария',
    gender: 'Женские',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 25,
    name: 'Seiko 5 Sports',
    description: 'Доступные автоматические часы. Надежный механизм, спортивный дизайн, дневная подсветка.',
    price: 18000,
    image: 'https://static.alltime.ru/obj/catalog/watch/ciga-design/img/normal2020/U031-BG01-W6B7B.jpg',
    article: 'SEIKO-5-029',
    country: 'Япония',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 26,
    name: 'Blancpain Fifty Fathoms',
    description: 'Первые в мире дайверские часы. Водонепроницаемость 300м, сапфировый безель.',
    price: 165000,
    image: 'https://static.alltime.ru/obj/catalog/watch/calvin-klein/img/normal2020/K2G226G6.jpg',
    article: 'BLANCPAIN-FF-030',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
  {
    id: 27,
    name: 'Michael Kors Lexington',
    description: 'Модные часы в стиле гламур. Блестящий браслет, кристаллы на циферблате.',
    price: 24000,
    image: 'https://static.alltime.ru/obj/catalog/watch/arbutus/img/normal2020/AR2404RBB.jpg',
    article: 'MK-LEX-031',
    country: 'США',
    gender: 'Женские',
    typeOfMechanism: 'Кварцевый',
  },
  {
    id: 28,
    name: 'Vacheron Constantin Patrimony',
    description: 'Ультратонкие элитные часы. Высшее часовое искусство, ручной завод, кожаный ремешок.',
    price: 289000,
    image: 'https://static.alltime.ru/obj/catalog/watch/swarovski/img/normal2020/5416023.jpg',
    article: 'VC-PATRIMONY-032',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Механический с ручным заводом',
  },
  {
    id: 29,
    name: 'Guess Connect',
    description: 'Стильные умные часы с сенсорным экраном. Уведомления, фитнес-трекинг, iOS/Android.',
    price: 19000,
    image: 'https://static.alltime.ru/obj/catalog/watch/dkny/img/normal2020/NY2769.jpg',
    article: 'GUESS-CONNECT-033',
    country: 'США',
    gender: 'Унисекс',
    typeOfMechanism: 'Электронный',
  },
  {
    id: 30,
    name: 'Audemars Piguet Royal Oak',
    description: 'Культовые часы со знаменитым "tapisserie" циферблатом. Стальной корпус, винты на безеле.',
    price: 312000,
    image: 'https://static.alltime.ru/obj/catalog/watch/pierre-ricaud/img/normal2020/P22038-91R3Q.jpg',
    article: 'AP-ROYALOAK-030',
    country: 'Швейцария',
    gender: 'Мужские',
    typeOfMechanism: 'Автоматический',
  },
];
